const books = [
  {
    id: 1,
    category: "Детективи",
    price: "13.99",
    stocked: true,
    name: "Десять негритят",
    author: "Агата Крісті",
    imageCover: "https://images.prom.ua/4872656290_desyat-negrenyat-agata.jpg",
    count: 1,
  },
  {
    id: 2,
    category: "Детективи",
    price: "15.99",
    stocked: true,
    name: 'Вбивство у "Східному експресі"',
    author: "Агата Крісті",
    imageCover:
      "https://knigoland.com.ua/upload/iblock/391/r9pjpv6fhc4uo792vpixhcb04u68xpkl/7955f380_6e14_11ec_815f_0050568ef5e6_865471aa_cf92_11ec_816f_0050568ef5e6.webp",
    count: 1,
  },
  {
    id: 3,
    category: "Детективи",
    price: "19.99",
    stocked: false,
    name: "Пригоди Шерлока Холмса",
    author: "Артур Конан Дойл",
    imageCover:
      "https://static.yakaboo.ua/media/cloudflare/product/webp/600x840/i/m/img383_1_43.jpg",
    count: 1,
  },
  {
    id: 4,
    category: "Фантастика",
    price: "29.99",
    stocked: true,
    name: "Володар перснів. Охоронці кільця",
    author: "Толкієн",
    imageCover:
      "https://upload.wikimedia.org/wikipedia/uk/0/0c/The_Fellowship_Of_The_Ring.jpg",
    count: 1,
  },
  {
    id: 5,
    category: "Фантастика",
    price: "39.99",
    stocked: false,
    name: "Володар перснів. Повернення короля",
    author: "Толкієн",
    imageCover: "https://www.kinofilms.ua/images/photos/w200/484698.jpg",
    count: 1,
  },
  {
    id: 6,
    category: "Фантастика",
    price: "30.99",
    stocked: true,
    name: "Гаррі Поттер і таємна кімната",
    author: "Джоан Роулінг",
    imageCover:
      "https://image.tmdb.org/t/p/original/ei6ciLYCz0GLUCQ1gw4wYtT2YvD.jpg",
    count: 1,
  },
  {
    id: 7,
    category: "Фантастика",
    price: "32.99",
    stocked: true,
    name: "Гаррі Поттер та в'язень Азкабану",
    author: "Джоан Роулінг",
    imageCover: "https://s2.vcdn.biz/static/f/5253752711/image.jpg",
    count: 1,
  },
];
export default books;
